name: Build Cassette Cross-Platform

on:
  workflow_dispatch:
    inputs:
      reason:
        description: 'Reason'
        required: false
        default: 'Manual Building'

jobs:
  build:
    name: Build on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: ubuntu-22.04
            artifact_name: linux-x64
            sep: ":"
          - os: windows-latest
            artifact_name: windows-x64
          - os: macos-15-intel
            artifact_name: macos-intel
          - os: macos-latest
            artifact_name: macos-silicon
            sep: ":"

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'
          cache: 'pip'

      - name: Install System Dependencies (Linux)
        if: runner.os == 'Linux'
        run: |
          sudo apt-get update
          sudo apt-get install -y libgl1-mesa-dev

      - name: Setup Venv and Install Project
        shell: bash
        run: |
          python -m venv venv
          if [ "${{ runner.os }}" == "Windows" ]; then
            source venv/Scripts/activate
          else
            source venv/bin/activate
          fi
          
          pip install -r requirements.txt
          pip install pyinstaller

      - name: Cleanup unnecessary files
        shell: bash
        run: |
          if [ "${{ runner.os }}" == "Linux" ]; then
            rm System/ADB/adb-macos
            rm System/ADB/adb.exe
            rm System/ADB/AdbWinApi.dll
            rm System/ADB/AdbWinUsbApi.dll
          elif [ "${{ runner.os }}" == "Windows" ]; then
            rm System/ADB/adb-macos
            rm System/ADB/adb-linux
          elif [ "${{ runner.os }}" == "macOS" ]; then
            rm System/ADB/adb-linux
            rm System/ADB/adb.exe
            rm System/ADB/AdbWinApi.dll
            rm System/ADB/AdbWinUsbApi.dll
          fi

          rm System/ADB/CassetteReceiver.apk

      - name: Run PyInstaller
        shell: bash
        run: |
          if [ "${{ runner.os }}" == "Windows" ]; then
            source venv/Scripts/activate
          else
            source venv/bin/activate
          fi

          pyinstaller --noconfirm cassette.spec

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: cassette-${{ matrix.artifact_name }}
          path: |
            ${{ runner.os == 'macOS' && 'dist/' || 'dist/Cassette' }}
            ${{ runner.os == 'macOS' && '!dist/Cassette' || '' }}
          include-hidden-files: true